import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { stampRedeemSchema, parseBody } from "@/lib/validation";
import { rateLimit, LIMITS } from "@/lib/rate-limit";
import { requireUser, tooManyRequests } from "@/lib/api-auth";

// Customer: redeem an owner-issued stamp code for one loyalty stamp.
// Customers can NOT stamp themselves — a valid, unexpired, unredeemed code
// generated by the business owner is required.
export async function POST(req: NextRequest) {
  const auth = await requireUser();
  if (auth.response) return auth.response;
  const userId = auth.user.id;

  const rl = rateLimit(`stamp:${userId}`, LIMITS.stamp.limit, LIMITS.stamp.windowMs);
  if (!rl.ok) return tooManyRequests(rl.retryAfterSeconds);

  let body: unknown;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid request body" }, { status: 400 });
  }
  const parsed = parseBody(stampRedeemSchema, body);
  if (!parsed.ok) return NextResponse.json({ error: parsed.error }, { status: 400 });
  const { businessId, code } = parsed.data;

  const business = await prisma.business.findFirst({ where: { id: businessId, active: true } });
  if (!business) return NextResponse.json({ error: "Business not found" }, { status: 404 });
  if (business.ownerId === userId) {
    return NextResponse.json({ error: "Owners cannot collect stamps at their own business" }, { status: 403 });
  }

  const config = await prisma.loyaltyConfig.findUnique({ where: { businessId } });
  if (!config || !config.active) {
    return NextResponse.json({ error: "Loyalty program not found" }, { status: 404 });
  }

  // Atomically claim the code: only succeeds if it is still unredeemed and unexpired.
  const claim = await prisma.stampCode.updateMany({
    where: {
      businessId,
      code,
      redeemedAt: null,
      expiresAt: { gt: new Date() },
    },
    data: { redeemedAt: new Date(), redeemedBy: userId },
  });
  if (claim.count === 0) {
    return NextResponse.json({ error: "Invalid or expired stamp code" }, { status: 400 });
  }

  const card = await prisma.loyaltyCard.upsert({
    where: { businessId_userId: { businessId, userId } },
    update: { stamps: { increment: 1 }, totalEarned: { increment: 1 } },
    create: { businessId, userId, stamps: 1, totalEarned: 1 },
  });

  // Auto-redeem the reward when the threshold is reached
  let redeemed = false;
  let finalCard = card;
  if (card.stamps >= config.stampsNeeded) {
    finalCard = await prisma.loyaltyCard.update({
      where: { businessId_userId: { businessId, userId } },
      data: { stamps: 0, rewardsClaimed: { increment: 1 } },
    });
    redeemed = true;
  }

  return NextResponse.json({ card: finalCard, redeemed, config });
}
